### ISSUE TITLE
file descriptor usage and emfile error

### ISSUE THREAD

**Issue by ringofhealth** [mtrudel/bandit#134]
We swapped in bandit to replace cowboy, noticing these kind of error that is popping up

```
[error] [label: {:erl_prim_loader, :file_error}, report: 'File operation error: emfile. Target: /Users/dev/code/elixir/helio/_build/dev/lib/bandit/ebin/Elixir.String.Chars.beam. Function: get_file. Process: code_server.']
```

followed by these errors

```
ogger - error: {removed_faiLogling_handler,'Egleirx - error: ir.Logger'}
{removed_failing_handler,'Elixir.Logger'}
=ERROR REPORT==== 22-Apr-2023::16:20:07.692381 ===
{error,simple_handler_process_dead}
rogger - error: {removed_failingLog_handler,'Elixir.Loggegre r-' }e
 22-Apr-2023::16:2ling_handLogger - error: le=rE,R'REOlRi xRiErP.OLRoTg=g=e=r='}
                  0:07.692350 ===
{error,simpl{er_ehandler_process_dead}
RmEovedR_failing_handler,'Elixir.LoggeRrO'R}
 EPORT==== 22-Apr-2023::16:20:07.692558 ===
{error,simple_handler_process_dead}
=DEBUG REPORT==== 22-Apr-2023::16:20:07.692363 ===
    logger: removed_failing_handler
    handler: {'Elixir.Logger','Elixir.Logger.Handler'}
    log_event: #{level => debug,
                 meta =>
                     #{file => "logger_backend.erl",gl => <0.0.0>,
                       internal_log_event => true,line => 71,
                       mfa => {logger_backend,call_handlers,3},
                       pid => <0.42.0>,time => 1682194807530000},
                 msg =>
                     {report,
                         [{logger,remove_handler_failed},
                          {reason,
                              {attempting_syncronous_call_to_self,
                                  {remove_handler,'Elixir.Logger'}}}]}}
    config: #{config =>
                  #{counter => {atomics,#Ref<0.3609761884.478543873.105489>},
                    sasl => false,
                    thresholds => {20,500},
                    translators =>
                        [{'Elixir.Plug.Cowboy.Translator',translate},
                         {'Elixir.Logger.Translator',translate}],
                    truncate => 8096,utc_log => false},
              formatter => {logger_formatter,#{}},
              id => 'Elixir.Logger',module => 'Elixir.Logger.Handler'}
    reason: {error,undef,
                [{'Elixir.Inspect',inspect,
                     [[{logger,remove_handler_failed},
                       {reason,
                           {attempting_syncronous_call_to_self,
                               {remove_handler,'Elixir.Logger'}}}],
                      #{'__struct__' => 'Elixir.Inspect.Opts',base => decimal,
                        binaries => infer,char_lists => infer,
                        charlists => infer,custom_options => [],
                        inspect_fun => fun 'Elixir.Inspect':inspect/2,
                        limit => 50,pretty => false,printable_limit => 4096,
                        safe => true,structs => true,syntax_colors => [],
                        width => 80}],
                     []},
                 {'Elixir.Kernel',inspect,2,
                     [{file,"lib/kernel.ex"},{line,2254}]},
                 {'Elixir.Logger.Handler',do_log,4,
                     [{file,"lib/logger/handler.ex"},{line,141}]},
                 {'Elixir.Logger.Handler',log,2,
                     [{file,"lib/logger/handler.ex"},{line,84}]}]}
=ERROR REPORT==== 22-Apr-2023::16:20:07.692729 ===
{error,simple_handler_process_dead}
=DEBUG REPORT==== 22-Apr-2023::16:20:07.692339 ===
    logger: removed_failing_handler
    handler: {'Elixir.Logger','Elixir.Logger.Handler'}
    log_event: #{level => debug,
                 meta =>
                     #{file => "logger_backend.erl",gl => <0.0.0>,
                       internal_log_event => true,line => 71,
                       mfa => {logger_backend,call_handlers,3},
                       pid => <0.42.0>,time => 1682194807515457},
                 msg =>
                     {report,
                         [{logger,remove_handler_failed},
                          {reason,
                              {attempting_syncronous_call_to_self,
                                  {remove_handler,'Elixir.Logger'}}}]}}
    config: #{config =>
                  #{counter => {atomics,#Ref<0.3609761884.478543873.105489>},
                    sasl => false,
                    thresholds => {20,500},
                    translators =>
                        [{'Elixir.Plug.Cowboy.Translator',translate},
                         {'Elixir.Logger.Translator',translate}],
                    truncate => 8096,utc_log => false},
              formatter => {logger_formatter,#{}},
              id => 'Elixir.Logger',module => 'Elixir.Logger.Handler'}
    reason: {error,undef,
                [{'Elixir.Inspect',inspect,
                     [[{logger,remove_handler_failed},
                       {reason,
                           {attempting_syncronous_call_to_self,
                               {remove_handler,'Elixir.Logger'}}}],
                      #{'__struct__' => 'Elixir.Inspect.Opts',base => decimal,
                        binaries => infer,char_lists => infer,
                        charlists => infer,custom_options => [],
                        inspect_fun => fun 'Elixir.Inspect':inspect/2,
                        limit => 50,pretty => false,printable_limit => 4096,
                        safe => true,structs => true,syntax_colors => [],
                        width => 80}],
                     []},
                 {'Elixir.Kernel',inspect,2,
                     [{file,"lib/kernel.ex"},{line,2254}]},
                 {'Elixir.Logger.Handler',do_log,4,
                     [{file,"lib/logger/handler.ex"},{line,141}]},
                 {'Elixir.Logger.Handler',log,2,
                     [{file,"lib/logger/handler.ex"},{line,84}]}]}
=DEBUG REPORT==== 22-Apr-2023::16:20:07.692544 ===
    logger: removed_failing_handler
    handler: {'Elixir.Logger','Elixir.Logger.Handler'}
    log_event: #{level => debug,
                 meta =>
                     #{file => "logger_backend.erl",gl => <0.0.0>,
                       internal_log_event => true,line => 71,
                       mfa => {logger_backend,call_handlers,3},
                       pid => <0.42.0>,time => 1682194807547755},
                 msg =>
                     {report,
                         [{logger,remove_handler_failed},
                          {reason,
                              {attempting_syncronous_call_to_self,
                                  {remove_handler,'Elixir.Logger'}}}]}}
    config: #{config =>
                  #{counter => {atomics,#Ref<0.3609761884.478543873.105489>},
                    sasl => false,
                    thresholds => {20,500},
                    translators =>
                        [{'Elixir.Plug.Cowboy.Translator',translate},
                         {'Elixir.Logger.Translator',translate}],
                    truncate => 8096,utc_log => false},
              formatter => {logger_formatter,#{}},
              id => 'Elixir.Logger',module => 'Elixir.Logger.Handler'}
    reason: {error,undef,
                [{'Elixir.Inspect',inspect,
                     [[{logger,remove_handler_failed},
                       {reason,
                           {attempting_syncronous_call_to_self,
                               {remove_handler,'Elixir.Logger'}}}],
                      #{'__struct__' => 'Elixir.Inspect.Opts',base => decimal,
                        binaries => infer,char_lists => infer,
                        charlists => infer,custom_options => [],
                        inspect_fun => fun 'Elixir.Inspect':inspect/2,
                        limit => 50,pretty => false,printable_limit => 4096,
                        safe => true,structs => true,syntax_colors => [],
                        width => 80}],
                     []},
                 {'Elixir.Kernel',inspect,2,
                     [{file,"lib/kernel.ex"},{line,2254}]},
                 {'Elixir.Logger.Handler',do_log,4,
                     [{file,"lib/logger/handler.ex"},{line,141}]},
                 {'Elixir.Logger.Handler',log,2,
                     [{file,"lib/logger/handler.ex"},{line,84}]}]}
=DEBUG REPORT==== 22-Apr-2023::16:20:07.692718 ===
    logger: removed_failing_handler
    handler: {'Elixir.Logger','Elixir.Logger.Handler'}
    log_event: #{level => debug,
                 meta =>
                     #{file => "logger_backend.erl",gl => <0.0.0>,
                       internal_log_event => true,line => 71,
                       mfa => {logger_backend,call_handlers,3},
                       pid => <0.42.0>,time => 1682194807562118},
                 msg =>
                     {report,
                         [{logger,remove_handler_failed},
                          {reason,
                              {attempting_syncronous_call_to_self,
                                  {remove_handler,'Elixir.Logger'}}}]}}
    config: #{config =>
                  #{counter => {atomics,#Ref<0.3609761884.478543873.105489>},
                    sasl => false,
                    thresholds => {20,500},
                    translators =>
                        [{'Elixir.Plug.Cowboy.Translator',translate},
                         {'Elixir.Logger.Translator',translate}],
                    truncate => 8096,utc_log => false},
              formatter => {logger_formatter,#{}},
              id => 'Elixir.Logger',module => 'Elixir.Logger.Handler'}
    reason: {error,undef,
                [{'Elixir.Inspect',inspect,
                     [[{logger,remove_handler_failed},
                       {reason,
                           {attempting_syncronous_call_to_self,
                               {remove_handler,'Elixir.Logger'}}}],
                      #{'__struct__' => 'Elixir.Inspect.Opts',base => decimal,
                        binaries => infer,char_lists => infer,
                        charlists => infer,custom_options => [],
                        inspect_fun => fun 'Elixir.Inspect':inspect/2,
                        limit => 50,pretty => false,printable_limit => 4096,
                        safe => true,structs => true,syntax_colors => [],
                        width => 80}],
                     []},
                 {'Elixir.Kernel',inspect,2,
                     [{file,"lib/kernel.ex"},{line,2254}]},
                 {'Elixir.Logger.Handler',do_log,4,
                     [{file,"lib/logger/handler.ex"},{line,141}]},
                 {'Elixir.Logger.Handler',log,2,
                     [{file,"lib/logger/handler.ex"},{line,84}]}]}
[error] GenServer #PID<0.2286.0> terminating
** (UndefinedFunctionError) function String.Chars.to_string/1 is undefined or private
    (elixir 1.14.2) String.Chars.to_string(:Host)
    (bandit 0.7.7) lib/bandit/http1/adapter.ex:99: Bandit.HTTP1.Adapter.do_read_headers/5
    (bandit 0.7.7) lib/bandit/http1/adapter.ex:27: Bandit.HTTP1.Adapter.read_headers/1
    (bandit 0.7.7) lib/bandit/http1/handler.ex:22: Bandit.HTTP1.Handler.handle_data/3
    (bandit 0.7.7) lib/bandit/delegating_handler.ex:18: Bandit.DelegatingHandler.handle_data/3
    (bandit 0.7.7) lib/thousand_island/handler.ex:332: Bandit.DelegatingHandler.handle_continue/2
    (stdlib 4.1.1) gen_server.erl:1123: :gen_server.try_dispatch/4
    (stdlib 4.1.1) gen_server.erl:865: :gen_server.loop/7
    (stdlib 4.1.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Last message: {:continue, :handle_connection}
State: {%ThousandIsland.Socket{socket: #Port<0.193>, transport_module: ThousandIsland.Transports.TCP, read_timeout: 60000, span: %ThousandIsland.Telemetry{span_name: :connection, telemetry_span_context: #Reference<0.3609761884.478412809.113572>, start_time: -576459296382418083, start_metadata: %{parent_telemetry_span_context: #Reference<0.3609761884.478412805.99344>, remote_address: {127, 0, 0, 1}, remote_port: 50434, telemetry_span_context: #Reference<0.3609761884.478412809.113572>}}}, %{handler_module: Bandit.InitialHandler, opts: %{http_1: [], http_2: [], websocket: []}, plug: {Phoenix.Endpoint.SyncCodeReloadPlug, {HelioWeb.Endpoint, []}}}}
[error] GenServer #PID<0.2282.0> terminating
** (stop) {%UndefinedFunctionError{module: String.Chars, function: :to_string, arity: 1, reason: nil, message: nil}, [{String.Chars, :to_string, [:Host], []}, {Bandit.HTTP1.Adapter, :do_read_headers, 5, [file: 'lib/bandit/http1/adapter.ex', line: 99]}, {Bandit.HTTP1.Adapter, :read_headers, 1, [file: 'lib/bandit/http1/adapter.ex', line: 27]}, {Bandit.HTTP1.Handler, :handle_data, 3, [file: 'lib/bandit/http1/handler.ex', line: 22]}, {Bandit.DelegatingHandler, :handle_data, 3, [file: 'lib/bandit/delegating_handler.ex', line: 18]}, {Bandit.DelegatingHandler, :handle_continue, 2, [file: 'lib/thousand_island/handler.ex', line: 332]}, {:gen_server, :try_dispatch, 4, [file: 'gen_server.erl', line: 1123]}, {:gen_server, :loop, 7, [file: 'gen_server.erl', line: 865]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 240]}]}
Last message: {:continue, :handle_connection}
State: {%ThousandIsland.Socket{socket: #Port<0.191>, transport_module: ThousandIsland.Transports.TCP, read_timeout: 60000, span: %ThousandIsland.Telemetry{span_name: :connection, telemetry_span_context: #Reference<0.3609761884.478412807.136017>, start_time: -576459296420648075, start_metadata: %{parent_telemetry_span_context: #Reference<0.3609761884.478412805.99340>, remote_address: {127, 0, 0, 1}, remote_port: 50430, telemetry_span_context: #Reference<0.3609761884.478412807.136017>}}}, %{handler_module: Bandit.InitialHandler, opts: %{http_1: [], http_2: [], websocket: []}, plug: {Phoenix.Endpoint.SyncCodeReloadPlug, {HelioWeb.Endpoint, []}}}}
[error] GenServer #PID<0.2285.0> terminating
** (UndefinedFunctionError) function String.Chars.to_string/1 is undefined or private
    (elixir 1.14.2) String.Chars.to_string(:Host)
    (bandit 0.7.7) lib/bandit/http1/adapter.ex:99: Bandit.HTTP1.Adapter.do_read_headers/5
    (bandit 0.7.7) lib/bandit/http1/adapter.ex:27: Bandit.HTTP1.Adapter.read_headers/1
    (bandit 0.7.7) lib/bandit/http1/handler.ex:22: Bandit.HTTP1.Handler.handle_data/3
    (bandit 0.7.7) lib/bandit/delegating_handler.ex:18: Bandit.DelegatingHandler.handle_data/3
    (bandit 0.7.7) lib/thousand_island/handler.ex:332: Bandit.DelegatingHandler.handle_continue/2
    (stdlib 4.1.1) gen_server.erl:1123: :gen_server.try_dispatch/4
    (stdlib 4.1.1) gen_server.erl:865: :gen_server.loop/7
    (stdlib 4.1.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Last message: {:continue, :handle_connection}
State: {%ThousandIsland.Socket{socket: #Port<0.192>, transport_module: ThousandIsland.Transports.TCP, read_timeout: 60000, span: %ThousandIsland.Telemetry{span_name: :connection, telemetry_span_context: #Reference<0.3609761884.478412807.136028>, start_time: -576459296385066446, start_metadata: %{parent_telemetry_span_context: #Reference<0.3609761884.478412805.99342>, remote_address: {127, 0, 0, 1}, remote_port: 50432, telemetry_span_context: #Reference<0.3609761884.478412807.136028>}}}, %{handler_module: Bandit.InitialHandler, opts: %{http_1: [], http_2: [], websocket: []}, plug: {Phoenix.Endpoint.SyncCodeReloadPlug, {HelioWeb.Endpoint, []}}}}
[error] GenServer #PID<0.2050.0> terminating
** (stop) an exception was raised:
    ** (UndefinedFunctionError) function String.Chars.to_string/1 is undefined or private
        (elixir 1.14.2) String.Chars.to_string(:Host)
        (bandit 0.7.7) lib/bandit/http1/adapter.ex:99: Bandit.HTTP1.Adapter.do_read_headers/5
        (bandit 0.7.7) lib/bandit/http1/adapter.ex:27: Bandit.HTTP1.Adapter.read_headers/1
        (bandit 0.7.7) lib/bandit/http1/handler.ex:22: Bandit.HTTP1.Handler.handle_data/3
        (bandit 0.7.7) lib/bandit/delegating_handler.ex:18: Bandit.DelegatingHandler.handle_data/3
        (bandit 0.7.7) lib/thousand_island/handler.ex:343: Bandit.DelegatingHandler.handle_info/2
        (stdlib 4.1.1) gen_server.erl:1123: :gen_server.try_dispatch/4
        (stdlib 4.1.1) gen_server.erl:1200: :gen_server.handle_msg/
```

this started happening after the swap with bandit, looks like there is an excess usage of the file descriptor, any guidance would be greatly appreciated!

**Comment by ringofhealth** [comment]
I do see that this is originating from `thousand_island`

https://github.com/mtrudel/thousand_island/issues/52

the way we are testing with bandit is on the readme where

```
config :helio, HelioWeb.Endpoint,
  adapter: Bandit.PhoenixAdapter,
```

**Comment by ringofhealth** [comment]
I think this is def coming from thousand island

```
Function: &ThousandIsland.Acceptor.run/1
    Args: [{#PID<0.1948.0>, #PID<0.2048.0>, %ThousandIsland.ServerConfig{port: 4000, transport_module: ThousandIsland.Transports.TCP, transport_options: [ip: {127, 0, 0, 1}], handler_module: Bandit.DelegatingHandler, handler_options: %{handler_module: Bandit.InitialHandler, opts: %{http_1: [], http_2: [], websocket: []}, plug: {Phoenix.Endpoint.SyncCodeReloadPlug, {HelioWeb.Endpoint, []}}}, genserver_options: [], num_acceptors: 100, num_connections: 16384, max_connections_retry_count: 5, max_connections_retry_wait: 1000, read_timeout: 60000, shutdown_timeout: 15000}}]
[error] Task #PID<0.2053.0> started from #PID<0.2051.0> terminating
** (RuntimeError) Unexpected error in accept: :emfile
    (thousand_island 0.6.7) lib/thousand_island/acceptor.ex:29: ThousandIsland.Acceptor.accept/5
    (elixir 1.14.2) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
    (stdlib 4.1.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Function: &ThousandIsland.Acceptor.run/1
    Args: [{#PID<0.1948.0>, #PID<0.2051.0>, %ThousandIsland.ServerConfig{port: 4000, transport_module: ThousandIsland.Transports.TCP, transport_options: [ip: {127, 0, 0, 1}], handler_module: Bandit.DelegatingHandler, handler_options: %{handler_module: Bandit.InitialHandler, opts: %{http_1: [], http_2: [], websocket: []}, plug: {Phoenix.Endpoint.SyncCodeReloadPlug, {HelioWeb.Endpoint, []}}}, genserver_options: [], num_acceptors: 100, num_connections: 16384, max_connections_retry_count: 5, max_connections_retry_wait: 1000, read_timeout: 60000, shutdown_timeout: 15000}}]
```

**Comment by ringofhealth** [comment]
we are running server with the following erl flags
```
export ELIXIR_ERL_OPTIONS="+P 500000 +A 64 +IOt 8"; \
    sh -c 'RUN_MODE=PROD iex -S mix phx.server'
```

**Comment by mtrudel** [comment]
I think your analysis is spot on:

* We're exhausting file handles (as you indicate, this is already reported at https://github.com/mtrudel/thousand_island/issues/52)
* This leaves the runtime unable to load `.../_build/dev/lib/bandit/ebin/Elixir.String.Chars.beam`, which means that there is no definition for `String.Chars.to_string(:Host)`, which is what the stack trace from Bandit is indicating.

Fundamentally, this is the same issue as https://github.com/mtrudel/thousand_island/issues/52; would you be able to answer any of the questions I'd asked of the original reporter there? The biggest problem with that bug is getting a repro case; I'm confident that the fix will be simple once I can see the issue happening. 

In the meantime, I'm going to close this issue; better that we consolidate the discussion over at https://github.com/mtrudel/thousand_island/issues/52

Thanks for the report!
