### ISSUE TITLE
`Bandit.Pipeline.handle_error` doesn't account for `Plug.Conn.WrapperError`

### ISSUE THREAD

**Issue by martosaur** [mtrudel/bandit#440]
I've been testing the new `log_client_closures` option and noticed that it doesn't always work. Depending on whether we use `Plug.Conn.send_resp` or `Plug.Conn.resp`, the error might be wrapped into a `Plug.Conn.WrapperError`. Here's a single file reproduction script:

```elixir
Mix.install([
  {:bandit, git: "http://github.com/mtrudel/bandit.git"},
  :mint
])

defmodule Router do
  use Plug.Router
  plug(Plug.Logger)
  plug(:match)
  plug(:dispatch)

  get "/" do
    Process.sleep(10_000)
    send_resp(conn, 200, "Hello, World!")
  end
end

bandit =
  {Bandit, plug: Router, scheme: :http, port: 4000, http_options: [log_client_closures: false]}

{:ok, _} = Supervisor.start_link([bandit], strategy: :one_for_one)

{:ok, conn} =
  Mint.HTTP.connect(:http, "localhost", 4000,
    protocols: [:http1],
    log: true,
    transport_opts: [linger: {true, 0}]
  )

{:ok, conn, request_ref} = Mint.HTTP.request(conn, "GET", "/", [], nil)
Process.sleep(2_000)
:gen_tcp.close(conn.socket)

# unless running from IEx, sleep idenfinitely so we can serve requests
unless IEx.started?() do
  Process.sleep(:infinity)
end
```

output:

```
14:24:34.096 [info] Running Router with Bandit 1.6.1 at 0.0.0.0:4000 (http)

14:24:34.120 [info] GET /

14:24:44.129 [info] Sent 200 in 10008ms

14:24:44.144 [error] ** (Plug.Conn.WrapperError) ** (Bandit.TransportError) Unrecoverable error: closed
    (bandit 1.6.1) lib/bandit/http1/socket.ex:437: Bandit.HTTPTransport.Bandit.HTTP1.Socket.socket_error!/1
    (bandit 1.6.1) lib/bandit/http1/socket.ex:367: Bandit.HTTPTransport.Bandit.HTTP1.Socket.send_data/3
    (bandit 1.6.1) lib/bandit/adapter.ex:230: Bandit.Adapter.send_data/3
    (bandit 1.6.1) lib/bandit/adapter.ex:113: Bandit.Adapter.send_resp/4
    (plug 1.16.1) lib/plug/conn.ex:444: Plug.Conn.send_resp/1
    /Users/amartsinovich/Library/Caches/mix/installs/elixir-1.17.3-erts-15.1.3/af70b3ae2c6b97b465ccbf93c26e832d/deps/plug/lib/plug/router.ex:246: anonymous fn/4 in Router.dispatch/2
    (telemetry 1.3.0) /Users/amartsinovich/Library/Caches/mix/installs/elixir-1.17.3-erts-15.1.3/af70b3ae2c6b97b465ccbf93c26e832d/deps/telemetry/src/telemetry.erl:324: :telemetry.span/3
    /Users/amartsinovich/Library/Caches/mix/installs/elixir-1.17.3-erts-15.1.3/af70b3ae2c6b97b465ccbf93c26e832d/deps/plug/lib/plug/router.ex:242: Router.dispatch/2
```

**Comment by grzuy** [comment]
Indeed.

For what is worth, the reason why this doesn't happens in bandit tests it's because there's no test case testing with `Plug.Router`, which is the one wrapping the error during dispatch: https://github.com/elixir-plug/plug/blob/80a4ee452d8161d7ee4b6042ca18ea6e9c9a8d70/lib/plug/router.ex#L250-L252.

**Comment by grzuy** [comment]
For what is worth, `plug_cowboy` does always unwrap `Plug.Conn.WrapperError` before re-raising:

https://github.com/elixir-plug/plug_cowboy/blob/ced253f035f2a07ebed17cfacb64d4f16357a750/lib/plug/cowboy/handler.ex#L43-L50

**Comment by grzuy** [comment]
Thanks @mtrudel for this and also for https://github.com/mtrudel/bandit/commit/0a3301a1b3ff84b337451d278cd5e40a24184d52 :clap:
